#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

export CHOST="arm-vita-eabi"

export rb_cv_arflags=rcu

## Aditional first search path can be defined here and added to configure command
# VITA_SEARCH_PATH="app0:lib/ruby/2.7.0/"
# --with-search-path="$VITA_SEARCH_PATH"

## Will rebuild libruby-static.a to include extensions at the end of compilation, default enabled.
# --enable/disable-libruby-with-exts

## Use Vita's SceFiber for coroutine implementation is the default, can be changed to copy
# --with-coroutine=[copy|scefiber]

## Default hard
# --with-vita-float-abi=[hard|softfp]

"$SCRIPT_DIR/configure" -C --host=$CHOST \
              --prefix="$VITASDK/$CHOST" \
              --cache-file=vita.cache \
              --enable-pthread=yes \
              --disable-rubygems \
              --disable-fortify-source \
              --disable-install-doc \
              CC=${CHOST}-gcc \
              CXX=${CHOST}-g++ \
              CFLAGS="-O3 -DNO_DEBUG"
